site_name: kmer-ord-docs
site_description: Read-level k-mer ordination for pre-assembly genome deconvolution
site_author: Frederik Deboever
site_url: https://FDBoever.github.io/kmer-ord-docs/

repo_name: FDBoever/kmer-ord
repo_url: https://github.com/FDBoever/kmer-ord
edit_uri: edit/main/docs/

theme:
  name: material
  font:
    text: Roboto
    code: Red hat Mono
  logo: assets/overview.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
  palette:
  #dark mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Dark mode
    primary: black
    accent: deep purple
  #light mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Light mode
    primary: black
    accent: deep organe

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md

  - Tutorials:
      - Tutorials overview: tutorials/index.md
      - Basic usage: tutorials/basic_usage.md
      - Advanced usage: tutorials/advanced_usage.md
  
  - Reference:
      - Reference overview: reference/index.md
      - k-mer counting: reference/kmer_counting.md
      - k-mer ordination: reference/kmer_ord.md

  - Concepts:
      - Concepts overview: concepts/index.md
      - K-mer counting: concepts/kmer_counting.md
      - Compositional data: concepts/compositional_data.md
      - Dimensionality reduction: concepts/dimensionality_reduction.md
      - Parameter screening: concepts/parameter_screening.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search

copyright: Copyright &copy; 2025 Frederik De Boever