site_name: kmer-ord
site_description: Read-level k-mer ordination for pre-assembly genome deconvolution
site_author: Frederik Deboever
site_url: http://127.0.0.1:8000/

repo_name: FDBoever/kmer-ord
repo_url: https://github.com/FDBoever/kmer-ord
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md

  - Concepts:
      - Overview: concept.md
      - K-mer manifolds: concepts/kmer_manifolds.md
      - Bin-then-assemble: concepts/bin_then_assemble.md

  - Tutorials:
      - Tutorials overview: tutorials.md

  - Figures:
      - Figures overview: figures/index.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - admonition

plugins:
  - search

